### ISSUE TITLE
Cannot run learned projection successfully

### ISSUE THREAD

**Issue by chihchiehchen** [j-zarka/separation_concentration_deepnets#1]
Hello,

Thanks for implementing and sharing the project. I am interested in scattering transform and want to see if it can be applied in the scenario with limited data. Following the commands from README.md I can reproduce the experiments on MNIST/CIFAR-10 successfully. However, when I try to use scattering with learned projections w/wo concentration, the error occurred:

> Traceback (most recent call last):
  File "main.py", line 778, in <module>
    main()
  File "main.py", line 117, in main
    main_worker(args)
  File "main.py", line 456, in main_worker
    args=args, logfile=logfile, summaryfile=summaryfile, writer=writer, is_training=True)
  File "main.py", line 566, in one_epoch
    input = model[j](input, j=j)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ccchen/projects/separation_concentration_deepnets/models/ScatNetAnalysis.py", line 27, in forward
    output = self.scattering(x)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/kymatio/frontend/torch_frontend.py", line 23, in forward
    return self.scattering(x)
  File "/home/ccchen/projects/separation_concentration_deepnets/phase_scattering2d_torch.py", line 80, in scattering
    S = phase_scattering2d(input, self.pad, self.unpad, self.backend, self.J, self.phis, self.psis)
  File "/home/ccchen/projects/separation_concentration_deepnets/phase_scattering2d_torch.py", line 109, in phase_scattering2d
    U_1_c = cdgmm(U_0_c, psi)  # (BC, L, M, N, 2)
  File "/home/ccchen/miniconda3/envs/cu_test/lib/python3.7/site-packages/kymatio/backend/torch_backend.py", line 190, in cdgmm
    raise RuntimeError('The filters are not compatible for multiplication.')
RuntimeError: The filters are not compatible for multiplication.

> 

I print out the sizes of U_0_c and psi, which are torch.Size([384, 1, 36, 36, 2]) and torch.Size([8, 36, 36, 1]), respectively.

The following are the packages of the environment:

> absl-py                 1.0.0
appdirs                 1.4.4
cachetools              5.0.0
certifi                 2021.10.8
charset-normalizer      2.0.11
configparser            5.2.0
cupy                    10.1.0
fastrlock               0.8
google-auth             2.6.0
google-auth-oauthlib    0.4.6
grpcio                  1.43.0
idna                    3.3
importlib-metadata      4.10.1
kymatio                 0.2.1
Mako                    1.1.6
Markdown                3.3.6
MarkupSafe              2.0.1
numpy                   1.21.5
oauthlib                3.2.0
packaging               21.3
Pillow                  9.0.1
pip                     22.0.3
protobuf                3.19.4
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycuda                  2021.1
pyparsing               3.0.7
pytools                 2021.2.9
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
scikit-cuda             0.5.3
scipy                   1.7.3
setuptools              59.5.0
six                     1.16.0
tensorboard             2.8.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
torch                   1.8.0+cu111
torchaudio              0.8.0
torchvision             0.9.0+cu111
typing_extensions       4.0.1
urllib3                 1.26.8
Werkzeug                2.0.3
wheel                   0.37.1
zipp                    3.7.0

> 

> 

Did I did something wrong? In any case thanks for help!

**Comment by chihchiehchen** [comment]
Finally I downgraded to torch 1.7.1 and everything works well, in any case thanks for the patient.
